# -*- coding: utf-8 -*-
"""blogger_js.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mEOdT9IrEpmbRI7Y8b81E1bXIfb33jJx
"""

from IPython.display import HTML
HTML("""
<script src="https://d3js.org/d3.v5.min.js"></script>
<div id="d3b01"></div><script>
var width=500,height=500,i=0;
var svg=d3.select("#d3b01").append("svg")
          .style("background","silver")
          .attr("width",width).attr("height",height);
var r=svg.append("rect")
         .attr("width",width).attr("height",height)
         .attr("fill","none").attr("pointer-events","all")
         .on("ontouchstart" in document ? 
             "touchmove":"mousemove",draw);
function draw(){var m=d3.mouse(this);
  svg.insert("circle","rect")
     .attr("fill",d3.hsl((i=(i+1)%720),1,.5))
     .attr("cx",m[0]).attr("cy",m[1]).attr("r",1e-6)
     .style("stroke","#fff").style("stroke-width",3)
     .style("stroke-opacity",1)
     .transition().duration(10000)
     .ease(Math.sqrt).attr("r",10)
     .style("stroke-opacity",1e-6).remove();
  d3.event.preventDefault();};
</script>""")

from IPython.display import HTML
HTML("""
<script src="//d3js.org/d3.v3.min.js"></script>
<svg id='d3b02' style='background-color:#101050;'></svg><script>
var width=250,height=250,ra=3*360,
    col=["silver","darkgray","slategray","darkslategray"],
    per=["40%","60%","80%","100%"];
var svg=d3.select("#d3b02")
          .attr("width",2*width).attr("height",2*height).append("g")
          .attr("transform","translate("+width+","+height+")");
var gradient=svg.append("defs")
                .append("linearGradient").attr("id","gradient")
                .attr("x1","0%").attr("y1","50%")
                .attr("x2","50%").attr("y2","100%");
for (var i=0; i<4; i++){
    gradient.append("stop").attr("offset",per[i])
                           .attr("stop-color",col[i]);};
svg.selectAll("path").data(d3.range(ra))
   .enter().append("path").attr("stroke","#fff")
   .attr("fill","url(#gradient)").attr("fill-opacity",.8)
   .attr("d",function(){return raindrop(Math.random()*100);})
   .attr("transform",function(d){
       return "rotate("+d+")"
              +"translate("+.9*height*Math.random()+",0)"
              +"rotate(270)";});
function raindrop(size){
  var r=Math.cos(Math.PI*size)+Math.sqrt(size);
  return "M"+r+",0"+"A"+r+","+r+" 0 1,1 "+-r+",0"
         +"C"+-r+","+-r+" 0,"+-r+" 0,"+-3*r
         +"C0,"+-r+" "+r+","+-r+" "+r+",0"+"Z";};
</script>""")

from IPython.display import HTML
HTML("""
<script src='https://d3js.org/d3.v4.min.js'></script>
<svg id='d3b03' style='background-color:ghostwhite;'></svg>
<script>
var n=6400,m=7,d=.001,margin={top:m,right:m,bottom:m,left:m},
    width=500-margin.left-margin.right,
    height=500-margin.top-margin.bottom,
    tr='translate('+margin.left+','+margin.top+')'; 
function fx(t,a,b,k){
    return Math.cos(d*t+k*Math.PI/6)+Math.cos(a*d*t)/2+Math.sin((a+b)*d*t)/3};
function fy(t,a,b,k){
    return Math.sin(d*t+k*Math.PI/6)+Math.sin(a*d*t)/2+Math.cos((a+b)*d*t)/3};
function randi(xmin,xmax){
    return Math.floor(Math.random()*(xmax-xmin+1))+xmin;};
function rcolor(i){
    var r=randi(i,255),g=randi(i,50),b=randi(i,255);
    return '#'+r.toString(16)+g.toString(16)+b.toString(16);}
var a=randi(7,15),b=randi(10,48);
function make_data(k){return d3.range(1,n).map(function(t){
    return {'x':fx(t,a,b,k),
            'y':fy(t,a,b,k)}});};    
var xScale=d3.scaleLinear()
             .domain([-2,2]).range([0,width+10]),
    yScale=d3.scaleLinear()
             .domain([-2,2]).range([height+10,0]); 
var svg=d3.select('#d3b03')
          .attr('width',width+margin.left+margin.right)
          .attr('height',height+margin.top+margin.bottom)
          .attr('transform',tr);
var line=d3.line().curve(d3.curveMonotoneX)
           .x(function(d){return xScale(d.x);})
           .y(function(d){return yScale(d.y);});
for (var i=1; i<m; i++) {var data=make_data(i),col=rcolor(i);
    svg.append('path').datum(data)
       .attr('class','line').attr('d',line)
       .attr('stroke',col).attr('fill','none');};
</script>""")