# -*- coding: utf-8 -*-
"""chart_building.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CtpL8akb2Hg7ITW5I3l9NcFcZY6F-YN0
"""

from IPython.display import display,HTML
import random
def colored_header(string):
    randi=random.randint(1,99999)
    display(HTML("""
<style>
@import 'https://fonts.googleapis.com/css?family=Akronim';
#col_header"""+str(randi)+"""
    {color:slategray; font-family:Akronim; 
     text-shadow:4px 4px 4px #aaa; padding-left:20px;}
</style>
<script>
var tc=setInterval(function() {
    var doc1=document.getElementById('col_header"""+str(randi)+"""');
    var now=new Date().getTime();
    var sec=Math.floor((now%60000)/6000);
    var col='rgb('+(10+Math.abs(245-8*sec))+',0,'+
            (255-Math.abs(245-8*sec))+')';
    doc1.style.color=col;}, 1000);
</script>
<h1 id='col_header"""+str(randi)+"""'>📑 """+string+"""</h1>"""))
colored_header('Barh Charts from HTML Elements')

from IPython.display import display,HTML
width=1100; data=[4,12,21,38,42,55]
chart_title='Building Bar Charts'
def barh_chart(data,chart_title,width,
               font_size=20,
               font_family='Wallpoet',
               background_color='#ff355e'):
    dmax=max(data); wbar=round(width/100*dmax*1.1)
    html_str="""
    <style>
    @import 'https://fonts.googleapis.com/css?family="""+font_family+"""'; 
    .div_params {padding:5px; width:"""+str(wbar)+"""px; 
                 text-align:right; text-shadow:4px 4px 4px slategray; 
                 color:lightgray; font-size:"""+str(font_size)+"""px; 
                 font-family:"""+font_family+"""; 
                 background:linear-gradient(
                     180deg,lightgray 0%,silver 33%,
                     slategray 67%, darkslategray 100%);}
    .div_params_in {background:"""+background_color+"""; 
                    padding:10px; margin:3px;}
    .div_h1 {text-shadow:4px 4px 4px slategray; 
             color:"""+background_color+"""; 
             font-family:"""+font_family+""";}
    </style>
    <div class='div_params'>
    <h2 class='div_h1'>"""+chart_title+"""</h2>"""
    for i in range(len(data)):
        html_str+="""
        <div class='div_params_in' 
        style='width:"""+str(width/100*data[i])+"""px;
        '>"""+str(data[i])+"""</div>"""
    html_str+="""</div><br/>"""
    display(HTML(html_str))
barh_chart(data,chart_title,width)

from IPython.display import display,HTML
import random

display(HTML("""
<style>
@import 'https://fonts.googleapis.com/css?family=Wallpoet';
#d3barchart_title {color:silver; font-family:Wallpoet; font-size:20px}
#d3barchart {width:60%; height:30%;}
</style>
<script src='https://d3js.org/d3.v6.min.js'></script>
<div id='d3barchart'><text id='d3barchart_title'></text></div>
<script>
var data=[4,12,21,38,42,55];
var tc=setInterval(function(){
    var now=new Date().getTime();
    var width=.6*Math.max(window.screen.width,window.innerWidth);
    var div=d3.select('#d3barchart');
    div.select('#d3barchart_title')
       .text('An Example of D3 Bar Charts');
    div.style('text-align','right')
       .style('text-shadow','3px 3px 3px slategray')
       .style('padding','5px')
       .style('color',d3.interpolateTurbo((now%60000)/60000))
       .style('background',d3.interpolateTurbo((now%60000)/60000));
    var x=d3.scaleLinear().domain([0,d3.max(data)])
            .range([0,.85*width]);
    div.selectAll('div').data(data).join('div')
       .style('background','silver')
       .style('padding','5px').style('margin','1px')
       .style('width',d=>x(d)+'px')
       .style('font-family','Wallpoet')
       .style('font-size','20px')
       .text(d=>d);},100);
</script>"""))